---
apiVersion: batch/v1
kind: Job
metadata:
    name: job-test
spec:
    completions: 20
    parallelism: 2
    template:
        metadata:
            name: job-test
        spec:
            containers:
            - name: for-loop
              image: centos:yum
              command: ["echo","hello world! "]
              #command: ["/bin/sh","-c"]
              #args:
              #  - sleep 30
            restartPolicy: Never
