---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nginx-s-d-h
spec:
    replicas: 2
    template:
        metadata:
            labels:
                app: nginx-s-d-h
        spec:
            containers:
            - name: nginx-s-d-h
              image: centos7.5:nginx-1.14.0
              ports:
              - containerPort: 80
              readinessProbe:
                  httpGet:
                      scheme: HTTP
                      path: /
                      port: 80
                  initialDelaySeconds: 10
                  periodSeconds: 5
              livenessProbe:
                  httpGet:
                      scheme: HTTP
                      path: /
                      port: 80
                  initialDelaySeconds: 10
                  periodSeconds: 5
              volumeMounts:
              - name: nginx-html2
                mountPath: /html/
            #kubectl label node k8s-node1 disktype=use_node (Configure and use the label)
            nodeSelector:
                disktype: use_node
            volumes:
            - name: nginx-html2
              hostPath:
                  path: /html2

---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: nginx2-service
    name: nginx-s-d-h
spec:
    type: NodePort
    selector:
        app: nginx-s-d-h
    ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
      nodePort: 30002

