---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: nginx-service
    name: nginx-svc
spec:
    type: NodePort #(需要配置nodePort时，要指明type为NodePort)
    selector:
        app: nginx-test
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001 #(30000-32767)
