apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
etcd:
  endpoints:
  - https://192.168.200.156:2379
  - https://192.168.200.157:2379
  - https://192.168.200.158:2379
  caFile: /etc/etcd/ssl/ca.pem
  certFile: /etc/etcd/ssl/etcd.pem
  keyFile: /etc/etcd/ssl/etcd-key.pem
  dataDir: /var/lib/etcd
networking:
  podSubnet: 10.244.0.0/16
kubernetesVersion: 1.10.0
api:
  advertiseAddress: "192.168.200.156"
token: "b99a00.a144ef80413d0822"
tokenTTL: "0s"
apiServerCertSANs:
- k8s-master
- k8s-node1
- k8s-node2
- 192.168.200.156
- 192.168.200.157
- 192.168.200.158
featureGates:
  CoreDNS: true
imageRepository: "registry.cn-hangzhou.aliyuncs.com/k8sth"
